from typing import Optional, Protocol

from app.scam_connector.models import ScamCase, Hotline, ScamPattern

class ScamConnector(Protocol):
    def get_case(self, case_id: str) -> Optional[ScamCase]: ...
    def search_patterns(self, query: str = "") -> list[ScamPattern]: ...
    def list_hotlines(self) -> list[Hotline]: ...